title: 'Product Category'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: category_description
        field:
          type: textarea
          display: 'Category Description'
      -
        handle: category_hero_image
        field:
          type: assets
          container: main
          restrict: false
          max_files: 1
          display: 'Category hero image'
      -
        handle: system_category
        field:
          type: terms
          max_items: 1
          mode: tags
          display: 'System Category'
          taxonomies:
            - system_category
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          validate:
            - required
  featured_in_product_category:
    display: 'Featured in Product Category'
    fields:
      -
        handle: feature_a_product
        field:
          default: false
          display: 'Feature a product?'
          type: toggle
          icon: toggle
          listable: hidden
          instructions_position: above
      -
        handle: product
        field:
          max_items: 1
          mode: default
          create: false
          collections:
            - products
          display: Product
          type: entries
          icon: entries
          instructions: 'Choose the product to feature in this category'
          listable: hidden
          instructions_position: above
          if:
            feature_a_product: 'equals true'
      -
        handle: add_custom_featured_text
        field:
          default: false
          display: 'Add custom Featured Text?'
          type: toggle
          icon: toggle
          listable: hidden
          instructions_position: above
          if:
            feature_a_product: 'equals true'
      -
        handle: featured_product_text
        field:
          always_show_set_button: false
          buttons:
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - anchor
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          display: 'Featured product text'
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          if:
            add_custom_featured_text: 'equals true'
taxonomies: true
