category_description: 'Headphones have been a popular product category for many years. Whether it is for music on the go or quality "personal" listening in one''s home, we offer a great selection of headphones for any budget.'
category_hero_image: rs1e-sidequarter-trans-1603917255.png
title: Headphones
system_category: headphones
blueprint: product_category
feature_a_product: true
product: 40113a77-84cd-4591-a1ae-f43c07aa4d62
updated_by: 87641989-b935-429e-81a7-ccf64c5d34d6
updated_at: 1697159665
add_custom_featured_text: false
featured_product_text:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Custom text'
