category_description: 'At Fidelis Music, the heart of the system is Amplification and we work with you to tie this together seamlessly with the speaker interface to produce involving musical experiences. With an array of high performance manufacturers like Moon, Boulder, McIntosh, Pass Labs, VAC, Exposure, Unison Research, Einstein, LFD, and others we offer our customers solutions that really perform!'
category_hero_image: 700i_v2_2-Tone_1370x590.png
callname: Amplifiers
title: 'Integrated Amplifiers'
system_category: amplification
blueprint: product_category
updated_by: 87ca4130-78f3-4ed1-8b64-aa552d3d08a8
updated_at: 1649880151
