category_description: 'The Swiss Army knives of audio - one box, many functions.'
category_hero_image: acamevo150.jpg
title: Multi-function
system_category: multi-function
blueprint: product_category
feature_a_product: true
product: af07f219-a883-4376-a321-e34d92a197db
add_custom_featured_text: false
updated_by: 87ca4130-78f3-4ed1-8b64-aa552d3d08a8
updated_at: 1697208123
