category_description: 'The Swiss Army knives of audio - one box, many functions.'
category_hero_image: acamevo150.jpg
title: Multi-function
system_category: multi-function
blueprint: product_category
