category_description: 'At Fidelis Music, the heart of the system is Amplification and we work with you to tie this together seamlessly with the speaker interface to produce involving musical experiences. With an array of high performance manufacturers like McIntosh, Pass Labs, VAC, Exposure, Unison Research, Einstein, and others we offer our customers solutions that really perform!'
category_hero_image: 860a_v2_2-tone_1370x590.png
feature_on_homepage: true
title: 'Power Amplifiers'
system_category: amplification
blueprint: product_category
feature_a_product: true
product: 0613892f-9ee2-4a17-91c9-4399734417ac
add_custom_featured_text: false
updated_by: 87ca4130-78f3-4ed1-8b64-aa552d3d08a8
updated_at: 1697209670
