category_description: 'Speakers are the centerpiece of your audio system and a very personal choice that must suit both your ears and the décor of your room. Speakers can bring out the very best in your music and here at Fidelis we’ve carefully evaluated the various brands of premium loudspeakers and our portfolio represents what we fell are the best options at all price-points.'
category_hero_image: olympica-nova-v-finishes-walnut.jpg
feature_on_homepage: true
title: Speakers
system_category: speakers
blueprint: product_category
feature_a_product: true
product: dd3273dc-a9d3-4fcf-9463-174850cb58b8
add_custom_featured_text: false
updated_by: 87ca4130-78f3-4ed1-8b64-aa552d3d08a8
updated_at: 1697205902
