category_description: 'Speakers are the centerpiece of your audio system and a very personal choice that must suit both your taste and the décor of your room. Speakers can bring out the very best in your music and here at Fidelis we’ve carefully evaluated the various brands of premium loudspeakers and our portfolio represents what we feel are the best options at all price-points.'
category_hero_image: olympica-nova-v-finishes-walnut.jpg
feature_on_homepage: true
title: Speakers
system_category: speakers
blueprint: product_category
feature_a_product: true
product: 08a91fce-c116-4b29-883d-a8f6dd8b486f
add_custom_featured_text: true
updated_by: 87ca4130-78f3-4ed1-8b64-aa552d3d08a8
updated_at: 1736522430
featured_product_text:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'I would sum up the performance of the Atalante 5 as full-bodied, detailed, and dynamic, with a wide and deep soundstage'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'The Ear'
