category_description: 'Bookshelf speakers need to be elevated off the floor for proper tonal balance and sound dispersion. We offer a wide variety of stands to suit any speaker and its requirements for height, platform size and overall rigidity.'
category_hero_image: ss6.jpg
title: Stands
system_category: setting
blueprint: product_category
updated_by: 87ca4130-78f3-4ed1-8b64-aa552d3d08a8
updated_at: 1649885921
