category_description: 'Adding a subwoofer isn''t just about improved low bass performance. A well set-up and high-performing subwoofer is capable of improving every aspect of sound - from overall tonal balance to the spaciousness of the sound field. We highly recommend an audition of one of our offerings from REL or Sonus Faber to see for yourself.'
category_hero_image: rel-s3_34view-300x293-1583610462.jpg
title: Subwoofers
system_category: speakers
blueprint: product_category
feature_a_product: true
product: 0723ad88-12e5-4ac4-b835-f7e625d7446b
add_custom_featured_text: false
updated_by: 87ca4130-78f3-4ed1-8b64-aa552d3d08a8
updated_at: 1697224535
